local awful = require("awful")

require("src.theme.user_variables")
require("src.theme.init")
require("src.core.error_handling")
require("src.core.signals")
require("src.core.notifications")
require("src.core.rules")
require("src.core.watches")
require("mappings.global_buttons")
require("mappings.bind_to_tags")
require("bar.init")

os.execute("xset r rate 220 30")
awful.spawn.with_shell("fcitx5")
awful.spawn("picom")
awful.spawn("kitty nvim vimwiki/index.wiki")
awful.spawn("kitty sudo pacman -Syu")
